image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS:   "4333796"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew
  # temporarily disable checking for EPIPE error and use yes to accept all licenses
  - set +o pipefail
  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
  - set -o pipefail

stages:
  - mavenbuild
  - maventest
  - mavenDeploy
  - androidbuild
  - androidtest


maven-build: #this is a JOB
  stage: mavenbuild
  tags:
    - charles_runner
  before_script:
    - export JAVA_HOME="/"

  script:
    - cd Backend/twin # to where you have the pom.xml
    - mvn package

maven-test:
   stage: maventest
   tags:
     - charles_runner
   before_script:
     - export JAVA_HOME="/"
   script:
     - cd Backend/twin
     - mvn test
   artifacts:
     paths:
       - Backend/target/*.jar


#Below job builds, deploys, executes jar as service.
autoDeploy:
  stage: mavenDeploy  #do make a stage with same name!
  tags:
  - charles_runner
  script:
    - cd Backend/twin
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo

android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  tags:
   - kaiheng9_runner
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/Twin/gradlew
  script:
    - cd Frontend/Twin # to where you have ‘gradlew’
    - ./gradlew build
  artifacts:
    paths:
    - Frontend/Twin/app/build/outputs/

android-test:
   image: gjandres/android-ci:latest
   stage: androidtest
   tags:
    - kaiheng9_runner
   before_script:
     - export GRADLE_USER_HOME=`pwd`/.gradle
     - chmod +x ./Frontend/Twin/gradlew
   script:
     - cd Frontend/Twin
     - ./gradlew test
