stages:
  - androidbuild
  - androidtest

android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  tags:
   - kaiheng9_runner
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/Android-MainProject/gradlew
  script:
    - cd Frontend # to where you have ‘gradlew’
    - ./Android-MainProject/gradlew build
  artifacts:
    paths:
    - Frontend/Android-MainProject/app/build/outputs/

android-test:
   image: gjandres/android-ci:latest
   stage: androidtest
   tags:
    - kaiheng9_runner
   before_script:
     - export GRADLE_USER_HOME=`pwd`/.gradle
     - chmod +x ./Frontend/Android-MainProject/gradlew
   script:
     - cd Frontend
     - ./Android-MainProject/gradlew test
