maven-build:
  stage: build
  tags:
    - backend-ezra
  script:
    - cd Backend/twin
    - mvn package

maven-test:
  stage: test
  tags:
    - backen-ezra
  script:
    - cd Backend/twin
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar
